language: java
jdk: # jdk versions to test against - https://www.deps.co/guides/travis-ci-latest-java/
- openjdk8 # oldest version we support. Do not use Oracle because the license expires.
- openjdk11 # most recent version supported by Travis
- openjdk-ea # early release - allow failures, but be aware that there *are* errors

matrix:
  allow_failures: # https://docs.travis-ci.com/user/build-matrix/#rows-that-are-allowed-to-fail
    - jdk: openjdk-ea # allow early access version to fail

before_deploy:
  # Begin Extract the project version
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  # End Extract

deploy:
  draft: false # set draft to true for testing - creates a draft build accessible only by collaborators
  name: $project_version # use the project version extracted in before_deploy as the name
  skip_cleanup: true # don't cleanup - we need the artifacts for deploying

  on:
    repo: gettyimages/gettyimages-api_java
    tags: true # only build tagged commits

  file:
    - gettyimagesapi-sdk/target/gettyimagesapi-sdk-$project_version.jar


  provider: releases # https://docs.travis-ci.com/user/deployment/releases

# GITHUB_PERSONAL_ACCESS_TOKEN is an environment variable set in Travis-CI
# https://travis-ci.org/gettyimages/gettyimages-api_java/settings
# It must be enabled for the branch you're working on.
  api_key: GITHUB_PERSONAL_ACCESS_TOKEN