language: java
jdk: # jdk versions to test against - https://www.deps.co/guides/travis-ci-latest-java/
- openjdk8 # oldest version we support. Do not use Oracle because the license expires.
- openjdk11 # most recent version supported by Travis
- openjdk-ea # early release - allow failures, but be aware that there *are* errors

matrix:
  allow_failures: # https://docs.travis-ci.com/user/build-matrix/#rows-that-are-allowed-to-fail
    - jdk: openjdk-ea # allow early access version to fail

before_deploy:
  # Begin Extract the project version
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  # End Extract

deploy:
  draft: false # set draft to true for testing - creates a draft build accessible only by collaborators
  name: $project_version # use the project version extracted in before_deploy as the name
  skip_cleanup: true # don't cleanup - we need the artifacts for deploying

  on:
    repo: gettyimages/gettyimages-api_java
    tags: true # only build tagged commits

  file: 
    - gettyimagesapi-sdk/target/gettyimagesapi-sdk-$project_version.jar
    
  provider: releases # https://docs.travis-ci.com/user/deployment/releases
  #
  # Releases instructions
  # if you need to change the api key 
  #   * install the travis client on your local machine (you will need Ruby installed)
  #       ** gem install travis
  #   * in the directory containing this yml file run the following command and follow the prompts
  #       ** travis setup releases
  #
  api_key:
    secure: QRDWEzr7ecy99uFYetCl6v0t1QSJKfAUJcMPxWQJNWohmzO1oxA7SJF+1PUqyj8cgP+ykZDrqdI3jHZCU+YPOtXirxDkxItc/uMsfJBQAaMlDLzIiZpx6husPAzvatp7xDC/KSRKfQlTv7NnP9oLt/hn8phTxHGyIssV6Xnpd/e84Uqu55NxyeuIfuTeEoVzuC8o4c5NpAClYASwgHV4l8e8uTDQqITx2Y/qbsukh/bq0TYLAQZkHf9GzhJ9Kfqo6p4vMybzn9bGUptf1c/gIUb/OckBTDC4yka3xHdTWvk+nlKPTPrO4LEeIrJ2JbT46ljBqaRzXmAEjr7A2l2rJd3xMOgD09Cb1Od+xiQ900hrh2o/0oSjcChRLZbRe/ztpe5SmJuyJcesBMM+wlvwwNE6hVc77BBCKvzen88OXHzgB8VX3ymKgz6adFKgNI614nemLcNP8/UyqqnjMf5rfknTp9rOkIxmmt9LNSapABCs2IJRlx5zQBup6ij3S66TL5JogEHsVxEzm1zn3vFOx2FJA+tRbd414eP0iB87Zi9tzI9z2/ZBkHTEUXnn22Y0w6W2fPJznTJ4NyJGMmgNLVvpmq0sl9KpfGp4rkof/kADhfxTIjUjRzc1UDHkiJHzxG/Tbw1Ojo+rQnj1RsestQ586tVvGOg0zhiapikGCOE=
